### ISSUE TITLE
vvw.py error

### ISSUE THREAD

**Issue by KwangryeolPark** [mit-han-lab/tinyengine#10]
Hello, I'm trying to do exmaple. However I encounter this error while executing "python vvw.py"

```
(pytorch) user:~/바탕화면/tinyengine$ python examples/vww.py 
Deriving the memory schedule for 41 activation tensors.
100%|██████████████████████████████████████████████████████████████████████████| 41/41 [00:00<00:00, 185109.22it/s]
Traceback (most recent call last):
  File "/home/user/바탕화면/tinyengine/examples/vww.py", line 28, in <module>
    peakmem = GenerateSourceFilesFromTFlite(
  File "/home/user/바탕화면/tinyengine/code_generator/CodegenUtilTFlite.py", line 54, in GenerateSourceFilesFromTFlite
    memory_scheduler.allocateMemory()
  File "/home/user/바탕화면/tinyengine/code_generator/GeneralMemoryScheduler.py", line 190, in allocateMemory
    self.allocator.visualize(self.mem_visual_path)
  File "/home/user/바탕화면/tinyengine/code_generator/allocator/base_allocator.py", line 240, in visualize
    plt.savefig(path, dpi=FIGURE_CONFIG["DPI"])
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/pyplot.py", line 942, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/figure.py", line 3272, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2338, in print_figure
    result = print_method(
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 520, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 466, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 408, in draw
    self.figure.draw(self.renderer)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/figure.py", line 3069, in draw
    mimage._draw_list_compositing_images(
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3099, in draw
    self.patch.draw(renderer)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/patches.py", line 589, in draw
    self._draw_paths_with_artist_properties(
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/patches.py", line 574, in _draw_paths_with_artist_properties
    renderer.draw_path(gc, *draw_path_args)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 149, in draw_path
    self._renderer.draw_path(gc, path, transform, rgbFace)
TypeError: must be real number, not str
```

**Comment by KwangryeolPark** [comment]
I fix the error.

**Comment by weitung** [comment]
I'm encountering the same bug, can you tell me how you fixed it?

**Comment by KwangryeolPark** [comment]
> I'm encountering the same bug, can you tell me how you fixed it?

See Setup for Users and Setup for Developers section in README.md file. 😁
