### ISSUE TITLE
No module named 'code_generator'

### ISSUE THREAD

**Issue by tracyyy19** [mit-han-lab/tinyengine#100]
So, I tried following the instructions of this tutorial, https://github.com/mit-han-lab/tinyengine/tree/main/tutorial/inference but I still get the same error

(tinyengine) C:\Users\USER\Downloads\tinyengine-main\tinyengine-main\examples>python vww.py
Traceback (most recent call last):
  File "vww.py", line 19, in <module>
    from code_generator.CodegenUtilTFlite import GenerateSourceFilesFromTFlite
ModuleNotFoundError: No module named 'code_generator'

**Comment by jin3qin** [comment]
Before running the Python script, you need to ensure that it runs in a conda environment with the configuration name **tinyengine**. If the "code_generator" module is missing, you need to run` export PYTHONPATH=${PYTHONPATH}: $(tinyengine's path)` first.

**Comment by jin3qin** [comment]
> So, I tried following the instructions of this tutorial, https://github.com/mit-han-lab/tinyengine/tree/main/tutorial/inference but I still get the same error
> 
> (tinyengine) C:\Users\USER\Downloads\tinyengine-main\tinyengine-main\examples>python vww.py Traceback (most recent call last): File "vww.py", line 19, in from code_generator.CodegenUtilTFlite import GenerateSourceFilesFromTFlite ModuleNotFoundError: No module named 'code_generator'

Before running the Python script, you need to ensure that it runs in a conda environment with the configuration name **tinyengine**. If the "code_generator" module is missing, you need to run `export PYTHONPATH=${PYTHONPATH}: $(tinyengine's path)` first.
