### ISSUE TITLE
No module named "cexample"

### ISSUE THREAD

**Issue by senceryucel** [mit-han-lab/tinyengine#66]
Hello, @meenchen

We were trying to integrate this beautiful engine into our H7 Plus Board. We changed the TARGET = OPENMV4 to OPENMV4P as needed. Everything seemed to be working fine, until we tried to run the example person detection script.

```

import cexample
import sensor


sensor.reset()  # Reset and initialize the sensor.
sensor.set_pixformat(sensor.RGB565)  # Set pixel format to RGB565 (or GRAYSCALE)
sensor.set_framesize(sensor.HD)  # Set frame size to QVGA 160x128

while True:
    img = sensor.snapshot()  # Take a picture and return the image.
    ret = cexample.person_detection(img, 0.15)

```
Since we have no LCD screen, we just modified the code a little to test it via frame buffer. However, when we run, it says that there is no module named "cexample".

We looked a bit in the repo for it, but could not find anything that would help us. Any help will be appreciated. Thanks a lot in advance!

**Comment by senceryucel** [comment]
Hi, @meenchen 

I did checkout to that commit. However, I believe what causes the problem is "sh gen_code.sh" part. Here is the error message I get when I try to run that command:

```
$ sh gen_code.sh
Traceback (most recent call last):
  File "examples/detection_fpn.py", line 19, in <module>
    from code_generator.CodeGenerator import CodeGenerator
  File "/home/senceryucel/Desktop/tinyengine/code_generator/CodeGenerator.py", line 112
    string += f"fptr = (float*){address_str}; for(i=0;i < {output.len};i++) v{output.name}[i] += "
                                                                                                 ^
SyntaxError: invalid syntax
mv: cannot stat 'codegen/': No such file or directory

```

I went to that specific python script to correct if there really exists a syntax error, but it seems like there are not any. What can I do? Thanks a lot in advance

**Comment by senceryucel** [comment]
Hi again, @meenchen 

Interestingly, I've successfully solved this syntax problem with changing string formats f"{string}" to "{}".format(string) one by one.

However, following is the problem I am trying to face, right now:

```
$ sh gen_code.sh
Traceback (most recent call last):
  File "examples/detection_fpn.py", line 19, in <module>
    from code_generator.CodeGenerator import CodeGenerator
  File "/home/senceryucel/Desktop/tinyengine/code_generator/CodeGenerator.py", line 22, in <module>
    from .OpGenerator import OpGenerator
  File "/home/senceryucel/Desktop/tinyengine/code_generator/OpGenerator.py", line 19, in <module>
    from .codetemplate.depthwiseTemplate import depthwiseInplace
ImportError: No module named codetemplate.depthwiseTemplate
mv: cannot stat 'codegen/': No such file or directory


```

**Comment by senceryucel** [comment]
Hey, @meenchen 

Yes, seems like that was the thing that causes to the error. Thank you!

Now, there occured another problem.

I have done everything correctly and it worked fine on my OpenMV H7 Board. It works amazing, I appreciate your work. However, when I try to run it on my OpenMV H7 Plus Board, I got an error at the last step of the building the firmware.

I changed TARGET=OPENMV4 to TARGET=OPENMV4P for both while building the source and while recompiling it. In building source part, everything works correctly. But I got the error below at the last step, while recompiling it:

```
 make[1]: Leaving directory '/home/senceryucel/Desktop/tinyengine/examples/openmv_person_detection/openmv/src/omv'
/usr/local/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /home/senceryucel/Desktop/tinyengine/examples/openmv_person_detection/openmv/src/build/bin/firmware.elf section `.text' will not fit in region `FLASH_TEXT'
/usr/local/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /home/senceryucel/Desktop/tinyengine/examples/openmv_person_detection/openmv/src/build/bin/firmware.elf section `.bss' will not fit in region `SRAM1'
/usr/local/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: section .dma_memory VMA [0000000030040000,0000000030043bff] overlaps section .bss VMA [0000000030000adc,0000000030042c8b]
/usr/local/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: section ._heap VMA [0000000030042c8c,000000003007ec8b] overlaps section .dma_memory VMA [0000000030040000,0000000030043bff]
/usr/local/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: section .d2_dma_memory VMA [0000000030043c00,0000000030047bff] overlaps section ._heap VMA [0000000030042c8c,000000003007ec8b]
/usr/local/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: region `SRAM1' overflowed by 257164 bytes
/usr/local/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: region `FLASH_TEXT' overflowed by 168120 bytes
collect2: error: ld returned 1 exit status
omv/ports/stm32/omv_portconfig.mk:649: recipe for target 'firmware' failed
make: *** [firmware] Error 1
make: Leaving directory '/home/senceryucel/Desktop/tinyengine/examples/openmv_person_detection/openmv/src'

```
What might be the cause for this? Thanks a lot in advance.
