### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by mashemat** [mit-han-lab/tinyengine#96]
Hello, 

I am trying to run the inference tutorial example but I receive the following error:

Downloading: "https://hanlab.mit.edu/projects/tinyml/mcunet/release/mcunet-5fps_vww.tflite" to /home/mashemat/.torch/mcunet/mcunet-5fps_vww.tflite
Traceback (most recent call last):
  File "/home/mashemat/Projects/MISO/code-base/tinyengine/mcunet/mcunet/utils/common_tools.py", line 104, in download_url
    urlretrieve(url, cached_file)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/vww.py", line 25, in <module>
    tflite_path = download_tflite(net_id="mcunet-vww1")
  File "/home/mashemat/Projects/MISO/code-base/tinyengine/mcunet/mcunet/model_zoo.py", line 91, in download_tflite
    return download_url(tflite_url)  # the file path of the downloaded tflite model
  File "/home/mashemat/Projects/MISO/code-base/tinyengine/mcunet/mcunet/utils/common_tools.py", line 108, in download_url
    os.remove(os.path.join(model_dir, 'download.lock'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/mashemat/.torch/mcunet/mcunet-5fps_vww.tflite/download.lock'

Could you please help me on that? It seems the file remove from the server.

Thanks,

**Comment by RaymondWang0** [comment]
Hi @mashemat, thank you for reaching out. The problem should be fixed now, so please try it again. I'll close the issue then. Feel free to reopen it if you have any further questions. Thanks!
